### ISSUE TITLE
Stale documentation?

### ISSUE THREAD

**Issue by adamhavel** [marko-js/marko-async#23]
Using the documentation and examples provided, I ran into few problems. First, the following snippet won't work:

  ```<async-fragment data-provider="data.fooProvider" var="foo" client-reorder="true">
   ${foo}
</async-fragment>```

When I try to compile this template, it throws an error: `The "data-provider" attribute value should not be a literal string`. It works if I strip the quotes from `data-provider` or put `#{...}` around the attribute.

The same thing applies to the `client-reorder` attribute. If I use it as stated in the documentation, nothing happens.The solution is yet again to declare the boolean value without the quotes.

As far as I understand the problem, it has to do with [the following changes](http://markojs.com/docs/marko/what-is-new-marko-v3/#attr-javascript-expressions) in Marko v3.

**Comment by patrick-steele-idem** [comment]
Sorry again for the confusion, I have updated the README.md to clarify that the Marko Async taglib source code and docs have been merged into the main `marko` repo. Please let me know if you still have questions or issues.
